[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_world = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
